apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
  namespace: squidgame
  labels:
    app: api-server
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: rabbitmq-pod