kind: Schedule
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: chaos-testing
  name: test3
spec:
  schedule: '@every 30s'
  startingDeadlineSeconds: null
  concurrencyPolicy: Allow
  historyLimit: 2
  type: PodChaos
  podChaos:
    selector:
      namespaces:
        - squidgame
      labelSelectors:
        app: kafka_pod
    mode: one
    action: pod-kill
    duration: 5s
    gracePeriod: 0
