# API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-pod
  namespace: squidgame
  name: kafka-pod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kafka-pod
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: kafka-pod
    spec:
      containers:
        - image: jaredosuna/fase3_api
          name: kafka-api
          env:
            - name: SERVER_IP
              value: "localhost"
            - name: SERVER_PORT
              value: "50051"
            - name: API_PORT
              value: "3000"
          ports:
            - containerPort: 3000
        - image: jaredosuna/fase3_producer
          name: kafka-producer
          env:
            - name: KAFKA_HOST
              value: "squidgame-cluster-kafka-bootstrap"
            - name: KAFKA_TOPIC
              value: "my-topic"
          ports:
            - containerPort: 50051
---
# API Service on port 3000
apiVersion: v1
kind: Service
metadata:
  name: kafka-pod
  namespace: squidgame
  labels:
    app: kafka-pod
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: kafka-pod