# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq-cluster
  name: rabbitmq-cluster
  namespace: squidgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-cluster
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq-cluster
    spec:
      containers:
      - image: rabbitmq:3.9-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources: {}
status: {}
---
# RabbitMQ Service on port 5672
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
  namespace: squidgame
  labels:
    app: rabbitmq-cluster
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app: rabbitmq-cluster