// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunPlayClient is the client API for RunPlay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunPlayClient interface {
	// Se envia la configuracion del juego
	SenConfigurationPlay(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error)
}

type runPlayClient struct {
	cc grpc.ClientConnInterface
}

func NewRunPlayClient(cc grpc.ClientConnInterface) RunPlayClient {
	return &runPlayClient{cc}
}

func (c *runPlayClient) SenConfigurationPlay(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (*PlayReply, error) {
	out := new(PlayReply)
	err := c.cc.Invoke(ctx, "/proto.RunPlay/SenConfigurationPlay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunPlayServer is the server API for RunPlay service.
// All implementations must embed UnimplementedRunPlayServer
// for forward compatibility
type RunPlayServer interface {
	// Se envia la configuracion del juego
	SenConfigurationPlay(context.Context, *PlayRequest) (*PlayReply, error)
	mustEmbedUnimplementedRunPlayServer()
}

// UnimplementedRunPlayServer must be embedded to have forward compatible implementations.
type UnimplementedRunPlayServer struct {
}

func (UnimplementedRunPlayServer) SenConfigurationPlay(context.Context, *PlayRequest) (*PlayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenConfigurationPlay not implemented")
}
func (UnimplementedRunPlayServer) mustEmbedUnimplementedRunPlayServer() {}

// UnsafeRunPlayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunPlayServer will
// result in compilation errors.
type UnsafeRunPlayServer interface {
	mustEmbedUnimplementedRunPlayServer()
}

func RegisterRunPlayServer(s grpc.ServiceRegistrar, srv RunPlayServer) {
	s.RegisterService(&RunPlay_ServiceDesc, srv)
}

func _RunPlay_SenConfigurationPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunPlayServer).SenConfigurationPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RunPlay/SenConfigurationPlay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunPlayServer).SenConfigurationPlay(ctx, req.(*PlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunPlay_ServiceDesc is the grpc.ServiceDesc for RunPlay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunPlay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RunPlay",
	HandlerType: (*RunPlayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SenConfigurationPlay",
			Handler:    _RunPlay_SenConfigurationPlay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fase2.proto",
}
