# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  namespace: squidgame
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: iguanav/front-sopes-f3:axios
          name: frontend
          ports:
            - containerPort: 3002
---
# Frontend Service on port 3002
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: squidgame
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: frontend