# Nodejs Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-backend
  namespace: squidgame
  name: nodejs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
        - image: iguanav/socket-sopes-f3
          name: nodejs-backend
          env:
            - name: HOSTREDIS
              value: "34.125.126.185"
            - name: HOSTTIDIS
              value: "34.125.195.218"
            - name: PORTDB
              value: "80"
          ports:
            - containerPort: 5000
---
# Nodejs Backend Service on port 5000
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-backend
  name: nodejs-backend
  namespace: squidgame
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nodejs-backend
  type: LoadBalancer
status:
  loadBalancer: {}