# Traffic Split -> Queue 2 50% ; Error 50%
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
  namespace: squidgame
spec:
  service: kafka-pod
  backends:
  - service: rabbitmq-pod
    weight: 500m
  - service: error-injector
    weight: 500m