# Traffic Split -> Queue 1 100%
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: service-split
  namespace: squidgame
spec:
  service: kafka-pod
  backends:
  - service: rabbitmq-pod
    weight: 1000m